### ISSUE TITLE
Parser fails with StopIteration error when searching for "Start SharedFunctionInfo" marker

### ISSUE THREAD

**Issue by asmirbe** [j4k0xb/View8#12]
## Bug Description
The V8 disassembler fails when parsing the disassembled file with a StopIteration error, indicating it cannot find the expected "Start SharedFunctionInfo" marker in the output.

## Environment
- Python version: 3.12.8
- V8 Disassembler version: Using binary 8.7.220.31.exe
- Operating System: Windows

## Steps to Reproduce
1. Run the disassembler with input file:
```py view8.py main.jsc main.js.txt```

## Error Output
```
C:\Users\usr\source\repos\V8Disassembler\x64\Release>V8Disassembler.exe main.jsc
Parameter count 1
Register count 1
Frame size 8
    0 S> 00000151081D0B3E @    0 : 82 00 00 00       CreateClosure [0], [0], #0
         00000151081D0B42 @    4 : 26 fa             Star r0
9073140 S> 00000151081D0B44 @    6 : ab                Return
Constant pool (size = 1)
00000151081D0B49: [FixedArray] in OldSpace
 - map: 0x015108042201 <Map>
 - length: 1
           0: 0x0151081d0b55 <SharedFunctionInfo>
Handler Table (size = 0)
Source Position Table (size = 9)
0x015108e0bdd9 <ByteArray[9]>
```

v8dasm used in this is from https://github.com/noelex/v8dasm with 8.7.220.31. The actual main.jsc file is itself a 8.7.220.31 V8 bytecode.
Output of the v8dasm.exe
```
Detecting version.
Detected version: 8.7.220.31.
Executing disassembler binary: C:\Users\usr\v8-disassembler\view8\Bin\8.7.220.31.exe.
Disassembly completed successfully.
Parsing disassembled file.
Traceback (most recent call last):
  File "C:\Users\usr\v8-disassembler\view8\view8.py", line 57, in <module>
    main()
  File "C:\Users\usr\v8-disassembler\view8\view8.py", line 50, in main
    all_func = disassemble(args.input_file, args.disassembled, args.path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\v8-disassembler\view8\view8.py", line 17, in disassemble
    return parse_disassembled_file(out_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\v8-disassembler\view8\Parser\parse_v8cache.py", line 61, in parse_disassembled_file
    all_func = parse_file(out_name)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\v8-disassembler\view8\Parser\sfi_file_parser.py", line 188, in parse_file
    while next(lines) != "Start SharedFunctionInfo":
          ^^^^^^^^^^^
StopIteration
```

## Expected Behavior
The parser should successfully find and parse the "Start SharedFunctionInfo" marker in the disassembled file.

## Actual Behavior
The parser raises a StopIteration error when trying to find "Start SharedFunctionInfo", suggesting either:
1. The disassembler output is empty
2. The output format has changed and doesn't contain the expected marker
3. The file is not being read correctly

## Additional Notes
The disassembly step reports success ("Disassembly completed successfully"), but the parsing fails immediately after, suggesting a potential mismatch between the disassembler output format and the parser's expectations.
I have not applied the v8.patch because Git tells me it is corrupt.
I only did what was in the v8dasm readme in the section: Modifying V8 Source Code

**Comment by j4k0xb** [comment]
> I have not applied the v8.patch because Git tells me it is corrupt.

This is required for View8, the disassembly output is slightly different than from the https://github.com/noelex/v8dasm guide

**Comment by asmirbe** [comment]
First of all thank you for a such detailed reply.
Also i encountered issues with offset_of which i solved by replacing by OFFSET_OF.
While getting corrupted `v8_libbase.lib` file if i don't set `use_lld = false` in `args.gn` file.

Concerning
```C++
os << "\nStart BytecodeArray\n";
this->GetActiveBytecodeArray().Disassemble(os);
os << "\nEnd BytecodeArray\n";
os << std::flush;```

The current V8 codebase (8.7.220.31) doesn't have a GetActiveBytecodeArray() method in the SharedFunctionInfo class.
I used `GetBytecodeArray` instead i guess it'll work ?
Same for 
```C++
if (map(cage_base).instance_type() == ASM_WASM_DATA_TYPE) {
  os << "<ArrayBoilerplateDescription> ";
  ArrayBoilerplateDescription::cast(*this)
      .constant_elements()
      .HeapObjectShortPrint(os);
  return;
}```
case_base is undefined in this function.
I guess i should change it to something like
```C++
if (map().instance_type() == ASM_WASM_DATA_TYPE) {
  os << "<ArrayBoilerplateDescription> ";
  ArrayBoilerplateDescription::cast(*this)
      .constant_elements()
      .HeapObjectShortPrint(os);
  return;
}
```

**Comment by j4k0xb** [comment]
yeah your changes should work

**Comment by asmirbe** [comment]
Ok after many tries i succed in building the disassambler so my jsc file is 12Mo when disassambled is 153 Mo (I definetly don't know if it's a normal size for an actual electron file).
After trying view8.py i get errors with the parser.

```
Executing disassembler binary: C:\Users\usr\Documents\GitHub\View8\Bin\8.7.220.31.exe.
Disassembly completed successfully.
Parsing disassembled file.
Traceback (most recent call last):
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 57, in <module>
    main()
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 50, in main
    all_func = disassemble(args.input_file, args.disassembled, args.path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 17, in disassemble
    return parse_disassembled_file(out_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\parse_v8cache.py", line 61, in parse_disassembled_file
    all_func = parse_file(out_name)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 190, in parse_file
    parse_shared_function_info(lines, "start")
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 171, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 124, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 115, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 84, in parse_const_line
    return var_idx, parse_shared_function_info(lines, value, func_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 171, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 124, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 115, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 84, in parse_const_line
    return var_idx, parse_shared_function_info(lines, value, func_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 171, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 124, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 115, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 70, in parse_const_line
    raise ValueError(f"Invalid constant line format: {var_line}")
ValueError: Invalid constant line format: ; #region FixedArray
```
disasm.tmp is 153Mo and 2m of lines long.
isolate file is 0.99Mo and has 11115 lines.

I can provide both for test actually but they are kinda heavy.

**Comment by j4k0xb** [comment]
> ValueError: Invalid constant line format: ; #region FixedArray

It's again being mixed with code from https://github.com/noelex/v8dasm
