### ISSUE TITLE
Error when parsing the disassembled file

### ISSUE THREAD

**Issue by silverwolfceh** [j4k0xb/View8#2]
```
python view8.py disasm.tmp main.js --disassembled
Parsing disassembled file.
Traceback (most recent call last):
  File "C:\Users\soiba\Desktop\SW\github\View8\view8.py", line 57, in <module>
    main()
  File "C:\Users\soiba\Desktop\SW\github\View8\view8.py", line 50, in main
    all_func = disassemble(args.input_file, args.disassembled, args.path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\view8.py", line 17, in disassemble
    return parse_disassembled_file(out_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\parse_v8cache.py", line 61, in parse_disassembled_file
    all_func = parse_file(out_name)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 189, in parse_file
    parse_shared_function_info(lines, "start")
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 167, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 122, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 113, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 82, in parse_const_line
    return var_idx, parse_shared_function_info(lines, value, func_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 167, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 122, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 113, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 82, in parse_const_line
    return var_idx, parse_shared_function_info(lines, value, func_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 167, in parse_shared_function_info
    sfi.const_pool = parse_const_pool(line, lines, sfi.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 122, in parse_const_pool
    return parse_const_array(lines, func_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 113, in parse_const_array
    next_idx, value = parse_const_line(lines, func_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soiba\Desktop\SW\github\View8\Parser\sfi_file_parser.py", line 70, in parse_const_line
    raise ValueError(f"Invalid constant line format: {var_line}")
ValueError: Invalid constant line format: Start ObjectBoilerplateDescription
```

It look like that parser not working for your patch of v8
[disasm.zip](https://github.com/user-attachments/files/16690816/disasm.zip)

**Comment by sussyGaymer** [comment]
Looking through `disasm.tmp` even more, I discovered things like this:
```
End BytecodeArray

End SharedFunctionInfo

Handler Table (size = 0)
Source Position Table (size = 15)
0x0c43cb783199 <ByteArray[15]>

End BytecodeArray

End SharedFunctionInfo

Handler Table (size = 0)
Source Position Table (size = 14)
0x0c43cb7831d1 <ByteArray[14]>

End BytecodeArray

End SharedFunctionInfo
```

Now, I see no logical way how this (ending a SharedFunctionInfo object 3 times in a row) makes sense, so I think different objects are being logged in parallel, therefore interrupting each other and creating this mess (see previous example).

**Comment by j4k0xb** [comment]
Yeah it's an upstream issue
The current way it works is by printing all disassembled objects recursively to the console, which is later parsed by regex (fails often)
I'm currently experimenting with writing each function/object/array/etc to a separate file, works pretty reliably

**Comment by sussyGaymer** [comment]
Any ETA on the release of that?

**Comment by j4k0xb** [comment]
fixed, build again with the new patch
